H_BASE=12;
H_LEAVES=4;
H_CONTROL_RING=4;
H_LEAF_GAP=10;
H_LINKS=3;

LINK_CONTROL_ANGLES=[0,24];
L_BOTTOM_LEAF_LINKS=[70,45];

H_SUPPORT_RING=12;

Z_LEAVES_1 = H_BASE;
Z_SUPPORT_1 = Z_LEAVES_1 + H_LEAF_GAP;
Z_LEAVES_2 = Z_SUPPORT_1 + H_SUPPORT_RING;
Z_SUPPORT_2 = Z_LEAVES_2 + H_LEAF_GAP;
Z_LEAVES_TOP = Z_SUPPORT_2 + H_SUPPORT_RING;

Z_CONTROL_RING=Z_SUPPORT_1 + H_SUPPORT_RING/2 - H_CONTROL_RING/2;
Z_CONTROL_RING_BEARING_STACK=Z_CONTROL_RING-8-3-6+1.5+H_CONTROL_RING;

CHAMFER_TOP_SUPPORT_RING = 10/sqrt(2);

R_CONTROL_RING_INNER=97;

R_STRUCTURE=180;
