use <bartscad/tr.scad>

H_BASE=12;
H_LEAVES=3.7;
H_CONTROL_RING=4;
H_LEAF_GAP=12;
H_LINKS=3;

LINK_CONTROL_ANGLES=[0,24];
L_BOTTOM_LEAF_LINKS=[70,45];

H_SUPPORT_RING=12;
H_TOP_SUPPORT_RING=16;

Z_LEAVES_1 = H_BASE;
Z_SUPPORT_1 = Z_LEAVES_1 + H_LEAF_GAP;
Z_LEAVES_2 = Z_SUPPORT_1 + H_SUPPORT_RING;
Z_SUPPORT_2 = Z_LEAVES_2 + H_LEAF_GAP;
Z_LEAVES_TOP = Z_SUPPORT_2 + H_TOP_SUPPORT_RING;

Z_CONTROL_RING=Z_SUPPORT_1 + H_SUPPORT_RING/2 - H_CONTROL_RING/2;
Z_CONTROL_RING_BEARING_STACK=Z_CONTROL_RING-8-3-6+1.5+H_CONTROL_RING+H_CONTROL_RING;

CHAMFER_TOP_SUPPORT_RING = 10/sqrt(2);

R_CONTROL_RING_INNER=85;
R_CONTROL_RING_BEARING=9.5;
R_CONTROL_RING_BEARING_MOUNT=R_CONTROL_RING_INNER-R_CONTROL_RING_BEARING;
ANGLE_CONTROL_RING_BEARING=38;

R_STRUCTURE=180;

D_TOP_LEAF_MOUNTING_SCREW=2;

OFFSET_TILT_ROLLER=145;
ANGLE_OFFSET_TILT_ROLLER=asin(OFFSET_TILT_ROLLER/(2*R_STRUCTURE));

Z_LIGHT_FIXTURE=Z_SUPPORT_2+9;
R_LIGHT_FIXTURE=150;
R_DIFFUSOR_DOME=450;
ANGLE_LIGHT_FIXTURE=-30;
