ANGLE_CENTER=180;

BEARING_INDEXES=[1,2,4];

TR_POWER_SUPPLY=rz(ANGLE_CENTER)*t(0,-30,Z_CONTROL_RING_BEARING_STACK);
TR_PCB=rz(ANGLE_CENTER)*t(10,29,Z_CONTROL_RING_BEARING_STACK+15)*rz(-90);

MM_PER_TOOTH=2.6;
TEETH_SERVO=25;
TEETH_CONTROL_RING=180;

ANGLE_CONTROL_RING_TRAVEL=ANGLE_CONTROL_RING_MAX-ANGLE_CONTROL_RING_MIN;

R_SERVO=72;
Z_SERVO=23.5;

TR_SERVO=rz(ANGLE_CENTER)*t(y=R_SERVO,z=Z_SERVO) * rx(-90);

POS_CABLE_GUIDE=[0,67];
R_SERVO_LINK=72;
SERVO_TRAVEL=R_SERVO_LINK*sin(ANGLE_CONTROL_RING_TRAVEL/2)*2;

OFFSET_Z_CONTROL_RAIL=8;
